LOAD LIBRARIES

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

LOAD DATA

In [ ]:
customers = pd.read_csv(r'customer.csv', on_bad_lines='skip', engine='c')
click_stream = pd.read_csv(r'click_stream.csv', on_bad_lines='skip', engine='c')
products = pd.read_csv(r'product.csv', on_bad_lines='skip', engine='c')
transactions = pd.read_csv(r'transactions.csv', on_bad_lines='skip', engine='c')

CLEAN DATA

CUSTOMERS

In [16]:
customers.head()

,customer_id,first_name,last_name,gender,birthdate,device_type,home_location,home_country,first_join_date
0,2870,Lala,Maryati,F,1996-06-14,iOS,Sumatera Barat,Indonesia,2019-07-21
1,8193,Maimunah,Laksmiwati,F,1993-08-16,Android,Jakarta Raya,Indonesia,2017-07-16
2,7279,Bakiman,Simanjuntak,M,1989-01-23,iOS,Nusa Tenggara Barat,Indonesia,2020-08-23
3,88813,Cahyadi,Maheswara,M,1991-01-05,iOS,Kalimantan Timur,Indonesia,2021-10-03
4,82542,Irnanto,Wijaya,M,2000-07-15,iOS,Kalimantan Selatan,Indonesia,2021-04-11

In [8]:
customers.dtypes

customer_id             int64
first_name                str
last_name                 str
username                  str
email                     str
gender                    str
birthdate                 str
device_type               str
device_id                 str
device_version            str
home_location_lat     float64
home_location_long    float64
home_location             str
home_country              str
first_join_date           str
dtype: object

In [9]:
customers.birthdate = pd.to_datetime(customers.birthdate, errors='coerce')
customers.first_join_date = pd.to_datetime(customers.first_join_date, errors='coerce')

In [10]:
customers.drop(columns=['username', 'email', 'device_id', 'device_version', 'home_location_lat', 'home_location_long'], inplace=True)

In [11]:
print(customers.isnull().sum() / len(customers) * 100)

customer_id        0.0
first_name         0.0
last_name          0.0
gender             0.0
birthdate          0.0
device_type        0.0
home_location      0.0
home_country       0.0
first_join_date    0.0
dtype: float64

PRODUCTS

In [22]:
products.sample(5)

,product_id,gender,masterCategory,subCategory,articleType,baseColour,season,year,usage,productDisplayName
16609,54689,Women,Apparel,Apparel Set,Kurta Sets,Green,Summer,2012,Ethnic,Shree Women Green and Blue Printed Patiala Kur...
14809,8845,Men,Apparel,Bottomwear,Trousers,Grey,Summer,2011,Casual,Scullers Men Scul Grey Trousers
34696,52129,Boys,Apparel,Topwear,Tshirts,White,Summer,2012,Casual,Doodle Boys white Printed T-Shirt
24331,9003,Women,Accessories,Bags,Handbags,Black,Winter,2015,Casual,Murcia Women Tote Black Handbags
35909,3809,Boys,Apparel,Topwear,Tshirts,Red,Summer,2011,Casual,Disney Kids Boy's He Is Behind You Red Kidswear

In [13]:
products.rename(columns={'id': 'product_id'}, inplace=True)

In [21]:
products.dtypes

product_id            int64
gender                  str
masterCategory          str
subCategory             str
articleType             str
baseColour              str
season                  str
year                  int64
usage                   str
productDisplayName      str
dtype: object

In [ ]:
print(products.isnull().sum() / len(products) * 100)

product_id            0.0
gender                0.0
masterCategory        0.0
subCategory           0.0
articleType           0.0
baseColour            0.0
season                0.0
year                  0.0
usage                 0.0
productDisplayName    0.0
dtype: float64

In [19]:
products.dropna(inplace=True)

In [20]:
products.year = products.year.astype(int)