LOAD LIBRARIES

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

LOAD DATA

In [9]:
customers = pd.read_csv('customers.csv')
geolocation = pd.read_csv('geolocation.csv')
orders = pd.read_csv('orders.csv')
order_items = pd.read_csv('order_items.csv')
order_payments = pd.read_csv('order_payments.csv')
order_reviews = pd.read_csv('order_reviews.csv')
products = pd.read_csv('products.csv')
sellers = pd.read_csv('sellers.csv')

CLEAN DATA

Customers

In [14]:
customers.shape

(1000000, 9)

In [10]:
customers.sample(5)

,customer_id,customer_unique_id,customer_name,customer_gender,customer_age,customer_zip_code_prefix,customer_city,customer_state,customer_segment
4881,6f1dc223-6bf7-42d5-919a-7ddd9049475f,4dd617ce-faca-405b-8537-7f1e09c4ea0b,Chloe Carter,F,35,10011,New York,NY,Consumer
442490,f0b652dd-46b5-4dad-91b3-2934cc54e35e,4b2240f1-42f8-4826-b727-afdf81901a07,Brittany Clark,F,34,10017,New York,NY,Consumer
96184,7f4fca76-7438-420d-ada9-c597f4348c15,ef04f446-cc47-4417-816f-7ef659ae96ba,Kristie Parrish,F,37,60614,Chicago,IL,Consumer
927749,c3c1161a-fca7-40ea-a032-a789eb2457a5,d491fbec-8182-4bfb-9f72-a4f112bd8466,Patricia Mcclain,F,19,30376,Atlanta,GA,Consumer
435681,400fd779-ccf6-4489-8010-2b6e4a8af956,8115340e-4262-417b-9f48-50578d225feb,Jamie Mccoy,F,37,90091,Los Angeles,CA,Consumer

In [11]:
print(customers.isnull().sum() /len(customers) * 100)

customer_id                 0.0
customer_unique_id          0.0
customer_name               0.0
customer_gender             0.0
customer_age                0.0
customer_zip_code_prefix    0.0
customer_city               0.0
customer_state              0.0
customer_segment            0.0
dtype: float64

In [12]:
customers.dtypes

customer_id                   str
customer_unique_id            str
customer_name                 str
customer_gender               str
customer_age                int64
customer_zip_code_prefix    int64
customer_city                 str
customer_state                str
customer_segment              str
dtype: object

In [13]:
customers = customers.drop_duplicates(subset='customer_id')

Geolocation

In [15]:
geolocation.shape

(11500, 5)

In [19]:
geolocation.sample(5)

      zip_code_prefix geolocation_city geolocation_state
8132            33172            Miami                FL
2376            90069      Los Angeles                CA
9682            19123     Philadelphia                PA
8367            33192            Miami                FL
8677            33162            Miami                FL

In [18]:
geolocation.drop(columns=['geolocation_lat','geolocation_lng'], inplace=True)

In [20]:
geolocation.dtypes

zip_code_prefix      int64
geolocation_city       str
geolocation_state      str
dtype: object

In [22]:
geoloation = geolocation.drop_duplicates(subset='zip_code_prefix')

Orders

In [51]:
orders.shape

(1000000, 6)

In [68]:
orders.sample(5)

,order_id,customer_id,order_purchase_timestamp,order_approved_at,order_estimated_delivery_date,delivered
619368,bb030301-ba52-4bf2-826b-832743c084e4,5cbd53d8-73bd-4e6b-85b9-2f00f830f662,2023-09-24 13:14:43,2023-09-24 15:12:43,2023-10-02 15:12:43,True
455390,391f3883-bdca-449e-8376-579f378e00a9,2287827f-13ea-43f9-93b7-e88f03be4f58,2021-03-24 19:35:50,2021-03-24 21:05:50,2021-04-03 21:05:50,True
507415,c4368909-959a-45be-ad2e-c6abec4257dd,3d1aaec7-d3df-4e0e-a844-3a25d0164189,2023-05-05 23:00:06,2023-05-06 06:52:06,2023-05-14 06:52:06,True
519403,976df553-2fce-49d2-a291-23ce033c1af8,9d7d4dfb-de93-4043-a31f-e294c2dd2173,2022-12-27 22:43:54,2022-12-27 23:16:54,2023-01-04 23:16:54,True
575382,7bf44a1c-3c20-4784-9ced-98844302a0bc,8ea85472-35cb-4459-9553-9814062edddb,2025-09-12 12:55:43,2025-09-12 16:45:43,2025-09-23 16:45:43,True

In [67]:
orders.dtypes

order_id                                    str
customer_id                                 str
order_purchase_timestamp         datetime64[us]
order_approved_at                datetime64[us]
order_estimated_delivery_date    datetime64[us]
delivered                                  bool
dtype: object

In [62]:
orders.order_status.nunique()

2

In [63]:
orders['delivered'] = orders.order_status.map({'delivered': True, 'canceled': False})

In [65]:
orders.drop(columns=['order_status'], inplace=True)

In [69]:
orders.drop(columns=['order_purchase_timestamp'], inplace=True)

In [58]:
orders.order_purchase_timestamp = pd.to_datetime(orders.order_purchase_timestamp)
orders.order_approved_at = pd.to_datetime(orders.order_approved_at)
orders.order_estimated_delivery_date = pd.to_datetime(orders.order_estimated_delivery_date)

In [43]:
orders.drop(columns=['order_delivered_carrier_date','order_delivered_customer_date'], inplace=True)

In [50]:
orders.drop_duplicates(subset='order_id', inplace=True)

Order_items

In [53]:
order_items.shape

(2199819, 8)

In [72]:
order_items.sample(5)

,order_id,order_item_id,product_id,seller_id,price,freight_value,discount_rate
1589937,4db0dec1-b53c-4bc8-b970-c68fe1c1a8a8,1,0a2c005b-d1e8-47f9-b707-aa1d52095e2f,096b6d24-6c99-4a3c-b8b6-c59191b6081f,96.84,6.65,0.0
1434752,524a6368-5463-4f95-aa7c-4883711a568f,2,602b044e-8a0c-476c-8100-4f350d8f9cf6,95f65a46-e14a-4408-9fb7-df5e97b2489c,937.94,134.67,0.0
1867306,3fa70868-2f55-4770-b86b-801e9e6a5377,2,4a1bcfca-0aff-44c8-9b90-ddc442cc7170,475d75cf-8a93-419b-811b-659ae637e0a2,24.14,5.92,0.0
18010,d9ec8875-24e2-4007-8604-f32956152a01,1,13605ef1-6af5-4600-83b4-3ee92d8186a0,cb446544-88d4-492c-af06-4cb81fd3456a,225.58,193.11,0.2
822935,ec7bfc99-37f3-4686-9019-0125ad1c5bf0,3,c358d926-1dce-4784-aafa-54f25c3fa039,28c39193-2741-4c65-b397-3227a3394a8f,96.46,76.24,0.0

In [52]:
order_items.drop_duplicates(inplace=True)

In [55]:
order_items.drop(columns=['shipping_limit_date'], inplace=True)

In [54]:
order_items.dtypes

order_id                   str
order_item_id            int64
product_id                 str
seller_id                  str
shipping_limit_date        str
price                  float64
freight_value          float64
discount_rate          float64
dtype: object

Order_payments

In [74]:
order_payments.shape

(1149371, 5)

In [87]:
order_payments.sample(5)

                                     order_id   payment_type  payment_value
776480   e99c89c5-d45e-41bc-a491-75b1cc447314    credit_card         202.41
1055754  159c93cb-5d80-45b5-bc48-77c2a421c569    credit_card         126.04
692845   52495347-dac2-488b-8560-9efbb8b10b4d  bank_transfer        1567.45
145762   9e8b7d4c-a4b3-403a-87d6-334db193e7ec         paypal         480.66
160215   14ac4300-30ae-41cd-bf97-0b95c3c45f07         paypal         411.88

In [86]:
order_payments.drop(columns=['payment_sequential', 'payment_installments'], inplace=True)

Sellers

In [80]:
sellers.sample(5)

,seller_id,seller_company_name,seller_contact_name,seller_contact_gender,seller_contact_age,seller_zip_code_prefix,seller_city,seller_state
74,a976a52e-5c44-4b51-ba95-c2a8ef7d2f4a,Hansen-Lopez,Jeffrey Patrick,M,48,90042,Los Angeles,CA
408,b72e51fd-1c58-42f6-abcd-3d43f712160f,Davidson-Anderson,Billy Hall,M,50,60672,Chicago,IL
188,605a3b06-2bda-44e0-91f2-d38ba687c317,Cohen and Sons,Angelica Dyer,F,27,77035,Houston,TX
476,e78d750d-45ac-4443-82e1-13194d02f5c5,Chang Group,Derrick Moreno,M,51,10050,New York,NY
95,2cc654c6-343d-46ec-bb72-eecc80c7dbe4,"Dawson, Thomas and Wilson",Kathy Chavez,F,33,33164,Miami,FL

In [81]:
sellers.dtypes

seller_id                   str
seller_company_name         str
seller_contact_name         str
seller_contact_gender       str
seller_contact_age        int64
seller_zip_code_prefix    int64
seller_city                 str
seller_state                str
dtype: object

Products

In [84]:
products.sample(5)

,product_id,product_category_name,product_name,product_brand,cost,price
365,272d828d-6382-4288-a800-dce84de698bf,home_goods,Nimbus Knife Set Set,Nimbus,65.94,150.61
418,0a2c005b-d1e8-47f9-b707-aa1d52095e2f,home_goods,Pulse Bedding - Cozy,Pulse,41.64,96.84
1559,e29fe69e-d1f5-44e8-8578-d8d67eacc5ab,home_goods,Apex Knife Set - Industrial,Apex,57.14,129.40
1128,824e76d9-4ff3-4ebc-8f57-df62ae436651,home_goods,Crest Lamp Set,Crest,6.33,12.90
908,201100a7-e782-4610-89b2-98cd2fbb8b26,books,Base over its,Pulse,23.67,40.10

In [83]:
products.drop(columns=['product_weight_g','product_length_cm','product_height_cm','product_width_cm'], inplace=True)

In [85]:
products.dtypes

product_id                   str
product_category_name        str
product_name                 str
product_brand                str
cost                     float64
price                    float64
dtype: object

Order_reviews

In [93]:
order_reviews.sample(5)

,review_id,order_id,review_score,review_comment_title
316717,c1ee9dc5-7f66-4f8f-ba1d-538daf208d70,64e4b389-7e9f-4a65-b902-400356be48d7,5,Excellent
376100,5fdb9de2-7719-46f6-a519-fdc2a2c882b7,df4ccd5b-bdd0-469b-926e-8f93d5df3a34,5,Fantastic
639014,09b5eafd-c8fe-4b88-8b11-28ca2b1f776c,5a1e1eb4-009f-46be-a778-3faef2e05a29,4,Amazing
643570,17aa82d8-6919-4623-9a5e-fd9dec674e37,01f452c0-e3cf-46ea-9c3a-4aa10a0914e4,5,Amazing
433054,ce975eb8-6f5b-4ebe-b04c-4346d1e1ffc3,d21ce45e-6a98-4a5e-968d-9f65062e0534,2,Late Delivery

In [90]:
order_reviews.drop(columns=['review_creation_date','review_answer_timestamp'], inplace=True)

In [92]:
order_reviews.drop(columns=['review_comment_message'], inplace=True)

MERGING

In [94]:
all = orders.merge(order_items, on='order_id').merge(order_payments, on='order_id').merge(order_reviews, on='order_id').merge(products, on='product_id').merge(sellers, on='seller_id').merge(customers, on='customer_id').merge(geolocation, left_on='customer_zip_code_prefix', right_on='zip_code_prefix')

In [96]:
all.drop(columns=['customer_zip_code_prefix','zip_code_prefix', 'order_id', 'customer_id'], inplace=True)

In [99]:
all.drop(columns=['product_id', 'seller_id', 'customer_unique_id', 'seller_zip_code_prefix', ], inplace=True)

In [105]:
all.drop(columns=['seller_city', 'seller_state', 'seller_contact_age', 'seller_contact_gender', 'review_id'], inplace=True)

In [109]:
all.drop(columns=['order_item_id', 'payment_value', 'seller_company_name'], inplace=True)

In [110]:
all.columns

Index(['order_approved_at', 'order_estimated_delivery_date', 'delivered',
       'price_x', 'freight_value', 'discount_rate', 'payment_type',
       'review_score', 'review_comment_title', 'product_category_name',
       'product_name', 'product_brand', 'cost', 'price_y',
       'seller_contact_name', 'customer_name', 'customer_gender',
       'customer_age', 'customer_city', 'customer_state', 'customer_segment',
       'geolocation_city', 'geolocation_state'],
      dtype='str')

In [111]:
all.sample(5)

,order_approved_at,order_estimated_delivery_date,delivered,price_x,freight_value,discount_rate,payment_type,review_score,review_comment_title,product_category_name,...,price_y,seller_contact_name,customer_name,customer_gender,customer_age,customer_city,customer_state,customer_segment,geolocation_city,geolocation_state
17532442,2024-09-28 12:01:35,2024-10-07 12:01:35,True,1406.79,116.58,0.0,credit_card,1,Late Delivery,electronics,...,1406.79,Eugene Johnson,Charles Cardenas,M,27,Los Angeles,CA,Consumer,Los Angeles,CA
5056457,2025-09-02 05:07:17,2025-09-12 05:07:17,True,234.32,169.02,0.0,debit_card,4,Perfect,furniture,...,234.32,Michael Robinson,Joshua Johnson,M,51,Houston,TX,Consumer,Houston,TX
3384065,2019-07-13 21:39:53,2019-07-22 21:39:53,True,63.34,62.22,0.2,credit_card,5,Great,fashion,...,79.17,Tara Davis,Amy Fletcher,F,35,New York,NY,Consumer,New York,NY
24888377,2021-11-29 16:42:44,2021-12-09 16:42:44,True,1966.83,202.60,0.0,credit_card,5,Perfect,electronics,...,1966.83,Nicholas Taylor,Lisa Morris,F,18,Los Angeles,CA,Consumer,Los Angeles,CA
44324817,2023-12-15 07:24:19,2023-12-24 07:24:19,True,117.30,199.24,0.0,credit_card,4,Great,home_goods,...,117.30,Curtis Cochran,Kelly Wall,F,30,New York,NY,Consumer,New York,NY

In [112]:
print(all.isnull().sum() / len(all) * 100)

order_approved_at                0.0
order_estimated_delivery_date    0.0
delivered                        0.0
price_x                          0.0
freight_value                    0.0
discount_rate                    0.0
payment_type                     0.0
review_score                     0.0
review_comment_title             0.0
product_category_name            0.0
product_name                     0.0
product_brand                    0.0
cost                             0.0
price_y                          0.0
seller_contact_name              0.0
customer_name                    0.0
customer_gender                  0.0
customer_age                     0.0
customer_city                    0.0
customer_state                   0.0
customer_segment                 0.0
geolocation_city                 0.0
geolocation_state                0.0
dtype: float64